# Generated by Django 5.0.6 on 2024-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('gig', models.PositiveBigIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('giftCardType', models.CharField(max_length=200)),
                ('otherGiftCardType', models.CharField(max_length=200)),
                ('giftCardAmount', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
