# Generated by Django 5.0.6 on 2024-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='giftCardAmount',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='giftCardType',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='otherGiftCardType',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='gig',
            field=models.TextField(),
        ),
    ]
