# Generated by Django 5.0.6 on 2024-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundleapp', '0002_remove_bundle_giftcardamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='number',
            field=models.TextField(null=True),
        ),
    ]
